---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sense-hat-display-dapr-workload
  namespace: azure-iot-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sense-hat-display-dapr-workload
  template:
    metadata:
      labels:
        app: sense-hat-display-dapr-workload
      annotations:
        dapr.io/enabled: "true"
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets"
        dapr.io/app-id: "sense-hat-display-dapr-workload"
        dapr.io/app-port: "8740"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-delay-seconds: "15"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "5"
        dapr.io/sidecar-readiness-probe-delay-seconds: "15"
        dapr.io/sidecar-readiness-probe-timeout-seconds: "5"
    spec:
      volumes:
        - name: dapr-unix-domain-socket
          emptyDir: {}
        - name: mqtt-client-token
          projected:
            sources:
              - serviceAccountToken:
                  path: mqtt-client-token
                  audience: aio-mq
                  expirationSeconds: 86400
        - name: aio-ca-trust-bundle
          configMap:
            name: aio-ca-trust-bundle-test-only
        - name: host-modules
          hostPath:
            path: /lib/modules
        - name: host-sys
          hostPath:
            path: /sys
      imagePullSecrets:
         - name: secret-au-custom-vision
      containers:
        - name: sense-hat-display
          image: crcustomvision.azurecr.io/sense-hat-display-arm64v8:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:  
          - containerPort: 7777
          volumeMounts:
          - name: host-modules
            mountPath: /lib/modules
          - name: host-sys
            mountPath: /sys
          env:
          - name: SENSE_HAT_DISPLAY_PORT
            value: "8740"
          - name: VERBOSE
            value: "False"

        - name: aio-mq-pubsub-pluggable
          image: ghcr.io/azure/iot-mq-dapr-components/pubsub:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: dapr-unix-domain-socket
            mountPath: /tmp/dapr-components-sockets
          - name: mqtt-client-token
            mountPath: /var/run/secrets/tokens
          - name: aio-ca-trust-bundle
            mountPath: /var/run/certs/aio-mq-ca-cert/
---
kind: Service
apiVersion: v1
metadata:
  name: sense-hat-display-service
  namespace: azure-iot-operations
  labels:
    app: sense-hat-display-dapr-workload
spec:
  selector:
    app: sense-hat-display-dapr-workload
  ports:
    - protocol: TCP
      port: 8740
      targetPort: 8740
  type: LoadBalancer
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: customvisionpubsub
  namespace: azure-iot-operations
spec:
  type: pubsub.aio-mq-pubsub-pluggable # DO NOT CHANGE
  version: v1
  #initTimeout: 1m
  metadata:
    - name: url
      value: "aio-mq-dmqtt-frontend:8883"
    - name: satTokenPath
      value: "/var/run/secrets/tokens/mqtt-client-token"
    - name: tlsEnabled
      value: true
    - name: caCertPath
      value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
    - name: logLevel
      value: "Info" 
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-statestore
  namespace: azure-iot-operations
spec:
  type: state.aio-mq-statestore-pluggable # DO NOT CHANGE
  version: v1
  metadata:
    - name: url
      value: "aio-mq-dmqtt-frontend:8883"
    - name: satTokenPath
      value: "/var/run/secrets/tokens/mqtt-client-token"
    - name: tlsEnabled
      value: true
    - name: caCertPath
      value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
    - name: logLevel
      value: "Info"
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerAuthorization
metadata:
  name: my-authz-policies
  namespace: azure-iot-operations
spec:
  listenerRef:
    - custom-vision-listener # change to match your listener name as needed
  authorizationPolicies:
    enableCache: false
    rules:
      - principals:
          attributes:
            - group: dapr-workload
        brokerResources:
          - method: Connect
          - method: Publish
            topics:
              - "$services/statestore/#"
          - method: Subscribe
            topics:
              - "clients/{principal.clientId}/services/statestore/#"            